### ISSUE TITLE
Issues with getting data to flow to Timestream

### ISSUE THREAD

**Issue by cpdk** [c33howard/signalk-to-timestream#2]
I have installed the latest (1.1.0) version on a SignalK server version 1.37.6 on a Raspberry PI and have issues with getting data into Timestream. In Timestream I see a lot of ListTables calls - but nothing else. I have given the PI timestream:* permissions. 

I have tried to enable debug logging but do not see anything - infact not even the "starting" text I see being logged upon plugin start... However I frequently see this line in the logs when changing the settings for the plugin: 

"Could not parse JSON options:Unexpected end of JSON input"

Not sure if related or not. I have double checked database name and tablename and have tried working with both include and exclude lists - with no changes in results.

Any tips, hints, ideas for debug would be much appreciated.

**Comment by c33howard** [comment]
Can you start the server with the env variable:

`DEBUG=signalk-to-timestream,signalk-to-timestream:trace`

The trace log stream will output the json that is sent to the server.

If you're not seeing 'starting', then something's going wrong before the plugin is being loaded.  Perhaps try clearing the plugin config in your plugin-config-data/ directory?  But that's just me guessing.

**Comment by cpdk** [comment]
Turned out to be a AWS permission issue - the SignalK user on Ubuntu did not have access to the AWS credentials - closing this issue.
